- name: create /etc/modules-load.d/k8s.conf
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf
    backup: yes
    owner: root
    group: root
    mode: '0644'

- name: modprobe overlay
  ansible.builtin.command: modprobe overlay

- name: modprobe br_netfilter
  ansible.builtin.command: modprobe br_netfilter

- name: Create /etc/sysctl.d/k8s.conf
  ansible.builtin.copy:
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    dest: /etc/sysctl.d/k8s.conf
    backup: yes
    owner: root
    group: root
    mode: '0644'

- name: sysctl --system
  ansible.builtin.command: sysctl --system
