- name: Discover swap status
  ansible.builtin.shell: cat /proc/swaps | wc -l
  register: swap_out

- name: Disable swap if it is enabled
  ansible.builtin.shell: |
    swapoff -a
  when: swap_out.stdout != "1"

- name: Enable memory cgroup
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^(.* rootwait)(?!.*cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1)( .*)?$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1\2'
    backrefs: yes
  register: cmdline_modified

- name: Reboot host if cmdline.txt was modified
  ansible.builtin.reboot:
  when: cmdline_modified.changed
