---
- name: Install Container Runtime
  ansible.builtin.apt:
    pkg:
      - containerd
      - containernetworking-plugins

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd/
    state: directory

- name: Configure containerd with cgroup driver
  ansible.builtin.copy:
    content: |
      version = 2
      [plugins]
        [plugins."io.containerd.grpc.v1.cri"]
          [plugins."io.containerd.grpc.v1.cri".containerd]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                runtime_type = "io.containerd.runc.v2"
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                  SystemdCgroup = true
    dest: /etc/containerd/config.toml
    backup: yes
    owner: root
    group: root
    mode: '0644'
